name: Ruby Push Gem

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.RubygemsApiKey }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need all the commits
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: actions/setup-node@v2
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump and Commit
        run: |
          yarn add standard-version
          yarn run standard-version
          git push --follow-tags
      - name: Push to rubygems.org
        run: |
          bundle exec gem release
